dist: xenial
sudo: true
services:
  - docker
language: node_js
node_js:
  - "12"
cache:
  directories:
    - node_modules
    - jspm_packages
install:
  - sudo apt-key update && sudo apt-get update && sudo apt-get -y install libcairo2-dev
    libjpeg-dev libpango1.0-dev libgif-dev build-essential g++
  - npm install
before_script:
  - DOCKER_IMAGE_NAME="q-chart"
  - DOCKER_TAG=${TRAVIS_BRANCH//[^a-zA-Z0-9\_\-\.]/_}
script:
  - npm run build
  - npm run test
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker build -t $DOCKER_IMAGE_NAME:$DOCKER_TAG .; fi'
after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then echo $DOCKER_PASSWORD | docker login -u="$DOCKER_USERNAME" --password-stdin; docker tag $DOCKER_IMAGE_NAME:$DOCKER_TAG nzzonline/$DOCKER_IMAGE_NAME:$DOCKER_TAG; docker push nzzonline/$DOCKER_IMAGE_NAME:$DOCKER_TAG; fi'
notifications:
  slack:
    secure: sGyFIyZQ73/Ub18pkrXDBcjKdOf3cN6teksTKmLf/5n5BGEWt1TNYWGeSA7IP7fFTQ9Ee131CqNM6WLd9CgG0anFPRhganWWFVOpGQAqAnO6U0RT3K4w0owzBai66dnYZpl8pOEVup8vaWXXNrEKg/gq3U2WHZWp/ekPY1VYy8hR3lTULuINU6EO6ZOjVHZx/tTBUUMLeU2PhPFIfTBQkdRSL4L2CgODFdX2xuRK79R/ApqZUe913F2ipsAkEhp8bHDiXpq5zuQBcMzBZH1zCZYdHelgugd1PgF3HJkR9pAu/mXG/JP4ybJ+d6NFZxlAmS46fDNW0/h+lVKytcbXqUpmH+jMRP94jzO9mpWgs0FUm3MerkOpKrZ0UzMOAHe5wt3wm3ey4jSOUiTvjmKCO/JjxCPURdEa5NJ44aez/U8HGlxODN+NO0FyFTPqce7SEgB3o/S+b5rKReaRBF2A2GoBhil8byM7b1MuN3qIgUFss0DRHWrzCrhQA9N9n+J1RTqvkwORbB5DPBsse4JHaKWahQOP6ZWKL26l90OARmZ7GmyVZG9/60psauNcIlC8eO162opUU2Ef19UT5VRGdLfwIc82YTlaMKEEGHV36S3Gh4VGgLtjGUiBYu+sDgDelHDP5bYSlF0neCrFrilDJRwCUO8XZQqundLYBTJiIGw=
